name: Generate Github Profile

on:
  # each day
  schedule:
    - cron: "0 16 * * *"

  # run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
    
jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: write

    steps:
      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            github-snake.svg?palette=github-light
            github-snake-dark.svg?palette=github-dark
      - name: Generate github metric
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: baopeg
          template: classic
          base: header, activity, community, repositories, metadata
          config_display: large
          config_octicon: yes
          config_timezone: Asia/Shanghai
          config_twemoji: yes
          plugin_calendar: yes
          plugin_calendar_limit: 2
          plugin_followup: yes
          plugin_followup_archived: yes
          plugin_followup_sections: user,repositories
          plugin_gists: yes
          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_people: yes
          plugin_people_limit: 24
          plugin_people_shuffle: yes
          plugin_people_size: 28
          plugin_people_types: followers, following
      - name: Push snake to gist
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gist_id: 4178cf7efa5a51a41b2a8f422bb65455
          gist_file_name: github-snake.svg
          file_path: github-snake.svg
      - name: Push dark snake to gist
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gist_id: 4178cf7efa5a51a41b2a8f422bb65455
          gist_file_name: github-snake-dark.svg
          file_path: github-snake-dark.svg
  keepalive-job:
    name: Keepalive Workflow
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
